dist: xenial

language: go
go: "1.14.x"
go_import_path: /skaffold

git:
  submodules: false

branches:
  only:
    - master

_integration_test: &integration_test
  os: linux
  language: minimal
  cache:
    directories:
      - $HOME/.cache/go-build
      - $HOME/.gradle
      - $HOME/.m2

# https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
# include in jobs where the docker version needs to be newer than what is shipped with xenial
_upgrade_docker: &upgrade_docker
  before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

jobs:
  include:
    - os: linux
      name: "linters"
      script:
        - make linters
    - os: linux
      name: "checks"
      script:
        - make checks
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: linux
      name: "Linux unit"
      script:
        - make coverage
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: osx
      name: "OSX unit"
      script:
        - make quicktest
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: windows
      name: "Windows unit"
      script:
        - go test -short -timeout 60s ./...
      cache:
        directories:
          - C:\\Users\\travis\\AppData\\Local\\go-build
    - name: "kind integration partition 0"
      <<: *integration_test
      script:
        - env IT_PARTITION=0 make integration-in-kind
    - name: "kind integration partition 1"
      <<: *integration_test
      script:
        - env IT_PARTITION=1 make integration-in-kind
    - name: "kind integration partition 2"
      <<: *integration_test
      script:
        - env IT_PARTITION=2 make integration-in-kind
    - name: "kind integration partition 3"
      <<: *integration_test
      script:
        - env IT_PARTITION=3 make integration-in-kind
    - name: "k3d integration partition 0"
      <<: *integration_test
      <<: *upgrade_docker
      script:
        - env IT_PARTITION=0 make integration-in-k3d
    - name: "k3d integration partition 1"
      <<: *integration_test
      <<: *upgrade_docker
      script:
        - env IT_PARTITION=1 make integration-in-k3d
    - name: "k3d integration partition 2"
      <<: *integration_test
      <<: *upgrade_docker
      script:
        - env IT_PARTITION=2 make integration-in-k3d
    - name: "k3d integration partition 3"
      <<: *integration_test
      <<: *upgrade_docker
      script:
        - env IT_PARTITION=3 make integration-in-k3d
    - os: linux
      name: "diag/Linux unit"
      script:
        - make -f Makefile.diag coverage
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: osx
      name: "diag/OSX unit"
      script:
        - make -f Makefile.diag test
      cache:
        directories:
          - $HOME/.cache/go-build
