apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    flags:
      install: ['--atomic']
      upgrade: ['--atomic']  
    releases:
    - name: skaffold-helm
      chartPath: charts
      values:
        image: skaffold-helm
