apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: test-file-sync
    jib:
      type: gradle
      args: 
      - -Psync
    sync:
      auto: {}

portForward:
- resourceType: pod
  resourceName: test-file-sync
  port: 8080
